language: node_js
node_js:
  - 14
services:
  - docker
script: 
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Tagging
  - docker tag udagram-api-feed luuanhdung93/udagram-api-feed:v1
  - docker tag udagram-api-user luuanhdung93/udagram-api-user:v1
  - docker tag udagram-api-frontend luuanhdung93/udagram-api-frontend:v1
  - docker tag udagram-reverseproxy luuanhdung93/udagram-reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push luuanhdung93/udagram-api-feed:v1
  - docker push luuanhdung93/udagram-api-user:v1
  - docker push luuanhdung93/udagram-api-frontend:v1
  - docker push luuanhdung93/udagram-reverseproxy:v1